### ISSUE TITLE
Motosim server unpack error

### ISSUE THREAD

**Issue by eastSpawn** [tingelst/moto#6]
Hi again!

I am getting an unpack error when I run the simulation server and moto_test.py
`python -i sim.py`
```
from moto.sim.motosim import ControlGroupSim, MotoSim

m = MotoSim("localhost", [ControlGroupSim(0, 6, [0.0] * 6)])
m.start()
```

`python moto_test.py`
```
from moto import motion_connection
from moto import Moto, ControlGroupDefinition
from moto.simple_message import (
    JointFeedbackEx,
    JointTrajPtExData,
    JointTrajPtFull,
    JointTrajPtFullEx,
    ValidFields,
)

import time
import numpy as np
import copy

m = Moto(
    "localhost",
    [
        ControlGroupDefinition(
            groupid="robot",
            groupno=0,
            num_joints=6,
            joint_names=[
                "joint_1_s",
                "joint_2_l",
                "joint_3_u",
                "joint_4_r",
                "joint_5_b",
                "joint_6_t",
            ],
        ),
    ],
    start_motion_connection=True,
    start_state_connection=True,
)


robot = m.control_groups["robot"]

time.sleep(1)


robot_joint_feedback: JointFeedbackEx = m.state.joint_feedback(groupno=0)

p0 = JointTrajPtFullEx(
    number_of_valid_groups=1,
    sequence=0,
    joint_traj_pt_data=[
        JointTrajPtExData(
            groupno=0,
            valid_fields=ValidFields.TIME | ValidFields.POSITION | ValidFields.VELOCITY,
            time=0.0,
            pos=robot_joint_feedback.pos,
            vel=[0.0] * 10,
            acc=[0.0] * 10,
        ),
    ],
)

p1 = JointTrajPtFullEx(
    number_of_valid_groups=1,
    sequence=1,
    joint_traj_pt_data=[
        JointTrajPtExData(
            groupno=0,
            valid_fields=ValidFields.TIME | ValidFields.POSITION | ValidFields.VELOCITY,
            time=5.0,
            pos=np.deg2rad([10.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]),
            vel=[0.0] * 10,
            acc=[0.0] * 10,
        ),
    ],
)
```

Console:
```
DEBUG:root:Setting motion update rate (hz): 100.000000
DEBUG:root:Setting initial joint state: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
DEBUG:root:Setting motion buffer size: 0
DEBUG:root:Starting motion worker in motion controller simulator
[motion_server]: Waiting for connection
[state_server]: Waiting for connection
[io_server]: Waiting for connection
>>> [motion_server]: Got connection from ('127.0.0.1', 59086)
[state_server]: Got connection from ('127.0.0.1', 59087)
[io_server]: Got connection from ('127.0.0.1', 59088)
Exception in thread Thread-2:
Traceback (most recent call last):
Exception in thread Thread-3:
  File "C:\Users\tehtt\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
Traceback (most recent call last):
  File "C:\Users\tehtt\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\tehtt\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self.run()
  File "C:\Users\tehtt\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\tehtt\AppData\Local\Programs\Python\Python39\lib\site-packages\moto\sim\motosim.py", line 112, in _worker
    self._target(*self._args, **self._kwargs)
  File "C:\Users\tehtt\AppData\Local\Programs\Python\Python39\lib\site-packages\moto\sim\motosim.py", line 187, in _worker
    msg = SimpleMessage.from_bytes(self._conn.recv(1024))
  File "C:\Users\tehtt\AppData\Local\Programs\Python\Python39\lib\site-packages\moto\simple_message.py", line 986, in from_bytes
    self._conn.sendall(msg.to_bytes())
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
    header = Header.from_bytes(bytes_[4:16])
  File "C:\Users\tehtt\AppData\Local\Programs\Python\Python39\lib\site-packages\moto\simple_message.py", line 174, in from_bytes
    return cls(*cls.struct_.unpack(bytes_))
struct.error: unpack requires a buffer of 12 bytes
```
Is this a bug? Or am I doing something wrong? Any help is appreciated.

**Comment by tingelst** [comment]
When you run the `test_moto.py` file you are not sending anything to the simulator or keeping the client alive. This is why you get this error, as it it automatically sends a package of zero length when you disconnect.

Try keeping the client alive: `python -i test_moto.py`

**Comment by eastSpawn** [comment]
That worked! Thank you!
